CC=g++
CFLAGS=-std=c++11 -c
INCLUDES=-I../../12/lib 

all: lib_13.o

lib_13.o: lib_13.h lib_13.cpp
	$(CC) $(CFLAGS) $(INCLUDES) lib_13.cpp

.PHONY: clean clean_lib_13

clean_lib_13:
	rm -rf lib_14.o

clean:
	rm -rf lib_14.o
